<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCx3hry5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCx3hry5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCx3hry5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCx3hry5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerCx3hry5\appDevDebugProjectContainer([
    'container.build_hash' => 'Cx3hry5',
    'container.build_id' => 'f3b3362b',
    'container.build_time' => 1737993537,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCx3hry5');
